created a sync utility with python, and created a function in bash to check if syncthing operations are complete, before we synchronize saves and we launch the game

diff --git a/gamesync-utilities b/gamesync-utilities
--- a/gamesync-utilities
+++ b/gamesync-utilities
@@ -9,3 +9,46 @@ log() {
   log_line="${datetime}|${content}"
   echo "$log_line" >> ~/.local/share/gamesync/log.log
 }
+
+check_syncthing() {
+  local API_KEY="$1"
+  local API_ADDRESS="$2"
+  local FOLDER_ID="$3"
+  local TIMEOUT=10
+  local start_time
+  start_time=$(date +%s)
+  local endpoint
+  endpoint="${API_ADDRESS}/rest/db/completion?folder=${FOLDER_ID}"
+
+  while true; do
+    local response
+    response=$(curl -s -H "X-API-Key: ${API_KEY}" -X GET "${endpoint}")
+    local sync_status
+    sync_status=$(echo "${response}" | grep -o '"completion": [0-9]*\(\.[0-9]\+\)\?' | cut -d ' ' -f 2)
+
+    if [[ -z "${sync_status}" ]]; then
+      log "Error retrieving status from ${endpoint}"
+      exit 2
+    fi
+
+    if [[ "${sync_status}" = "Not Authorized" ]]; then
+      log "Invalid API key used"
+      exit 3
+    fi
+
+    if [ "${sync_status}" = "100" ]; then
+      log "Folder is completely synchronized."
+      break
+    fi
+
+    local current_time
+    current_time=$(date +%s)
+    local elapsed_time=$((current_time - start_time))
+    if [ $elapsed_time -ge $TIMEOUT ]; then
+      log "Timeout reached. Folder synchronization did not complete."
+      exit 1
+    fi
+
+    sleep 1
+  done
+}
